[assembly: AssemblyTitle("Wice.Tests")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("Wice.Tests")]
[assembly: AssemblyCopyright("Copyright ©  2020-2026")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(false)]
[assembly: Guid("047db52b-db07-4cf6-be90-c24819629c7e")]
